### ISSUE TITLE
How to get frame delays?

### ISSUE THREAD

**Issue by Dingo64** [galfar/imaginglib#13]
I can load APNG and GIF animations without problems:

```
LoadMultiImageFromFile(Filename, Images);
for i:=0 to Length(Images) do ImagingComponents.ConvertDataToBitmap(Images[i], Bmp);
```

But how do I get delays, fps or some other information to know how long each frame should be visible before rendering next frame?

**Comment by galfar** [comment]
Frame delays and looping are captured in GlobalMetadata variable after loading. Access it like this:
`Delay := GlobalMetadata.MetaItemsMulti[SMetaFrameDelay];`

Take a look around here https://github.com/galfar/imaginglib/blob/master/Source/Imaging.pas#L603 for more info.

**Comment by Dingo64** [comment]
Thanks for a fast reply!
I also discovered I can just do it this way:

```
Pic := TGIFFileFormat.Create(Meta);
Res := Pic.LoadFromFile(Filename, Images, False);
Delay := Meta.MetaItemsMulti['FrameDelay', Index];
```
