### ISSUE TITLE
Compiler error while building package: Missing file ImagingExtras.pas

### ISSUE THREAD

**Issue by riaanjutte** [galfar/imaginglib#16]
Trying to build the package in Delphi 10.3 results in this error:

[dcc32 Fatal Error] VampyreImagingPackage.dpk(130): F1026 File not found: '..\Extensions\ImagingExtras.pas'

**Comment by galfar** [comment]
Thanks for the report, fixed in 20e52e105cc954a3699a3d92d6effb244a0cd0ed.
