### ISSUE TITLE
Suggestion: LoadFromBits

### ISSUE THREAD

**Issue by hafedh-trimeche** [galfar/imaginglib#28]
Hello,

Would you please add a function (or indicate how) which creates image from Raw bits:
`function LoadFromBits(const Bits:Pointer;AWidth,AHeight,BitsPerPixel:Integer):Boolean;
`

Best regards.

**Comment by galfar** [comment]
Hi, you can use `ReadRawImageFromMemory` (and related) functions (look in Imaging.pas unit).

Example:
```pascal
var Img: TImageData;

ReadRawImageFromMemory(DataBits, DataSizeInBytes, 256, 256, ifA8R8G8B8, Img);
```
