### ISSUE TITLE
Interference with TImage

### ISSUE THREAD

**Issue by Alienizering** [galfar/imaginglib#29]
Hello,

First, let may thank you for this fabulous package and I appreciate that it's also free. It works perfectly.

This issue for for Windows OS (I use Win10/64).

There is one issue I found. If you start a new project, place a TImage on the form and load a picture in the TImage, save the test project and re-open it, you'll get a Image1.Picture.Data stream error upon viewing the form.

Now if you uninstall the Vampyre package and reload the test project, it loads fine and no error and the picture shows in the TImage.

I hope you know why and can fix it easily. 

Again, thank you so much.

-Alan

**Comment by Alienizering** [comment]
0.82 fixed that, duh! Sorry :)

**Comment by galfar** [comment]
There are even more outstanding problems with auto registration in TPicture, it will be removed sometime in future.
