### ISSUE TITLE
Having a problem running VCL demo

### ISSUE THREAD

**Issue by ZaakaJarimbo** [galfar/imaginglib#34]
### Discussed in https://github.com/galfar/imaginglib/discussions/33

<div type='discussions-op-text'>

<sup>Originally posted by **ZaakaJarimbo** January 14, 2023</sup>
I have just downloaded and setup the Imaging library, however, when trying to run the VCL Demo I get errors :( see attached link, does anyone know what I have done wrong?

[https://www.teeseyed.online/i1.jpg](url)
![Imaging1](https://user-images.githubusercontent.com/5955746/212446965-1b7460a6-5ee0-4d6a-853d-0a7d82d776e8.jpg)
</div>

**Comment by galfar** [comment]
I could not reproduce this with Delphi 11.3, which version exactly did you use?

**Comment by galfar** [comment]
Actually, that is some very old revision of the code.

It's been looking like this for years:

``` delphi
procedure TSingleImage.Assign(Source: TPersistent);
begin
  if Source = nil then
  begin
    Clear;
  end
  else if Source is TSingleImage then
  begin
    AssignFromImageData(TSingleImage(Source).FImageData);
  end
  else if Source is TMultiImage then
  begin
    if TMultiImage(Source).Valid then
      AssignFromImageData(TMultiImage(Source).FPData^)
    else
      Clear;
  end
  else
    inherited Assign(Source);
end;
```
