### ISSUE TITLE
unregistering TPortableNetworkGraphic causes empty images in forms

### ISSUE THREAD

**Issue by olivluca** [galfar/imaginglib#39]
I'm using the Vampyre imaging library without installing it in the ide, just as a runtime package.
If I put an image with a png picture in a form, at run time the image isn't shown.
That's because of [this line](https://github.com/galfar/imaginglib/blob/4627e3b48865a8b707e0d576ab4cd4df0550fea3/Source/ImagingComponents.pas#L452)

```
{$IFNDEF DONT_LINK_PNG}
  {$IFDEF COMPONENT_SET_LCL}
    // Unregister Lazarus default PNG loader which crashes on some PNG files
    TPicture.UnregisterGraphicClass(TPortableNetworkGraphic);
  {$ENDIF}
  RegisterFileFormat(TImagingPNG);
  Classes.RegisterClass(TImagingPNG);
{$ENDIF}

```

I don't think that's a good idea, even if, as the comment says, the default png loader crashes on some files. With this line it doesn't work with **every** file.

See also the mailing list thread starting [here](https://lists.lazarus-ide.org/pipermail/lazarus/2022-June/239836.html) (which also explains why I don't install the library in the ide) and my latest message [two years later](https://lists.lazarus-ide.org/pipermail/lazarus/2024-July/240915.html)

**Comment by galfar** [comment]
I'd hope the PNG loader in Lazarus has been fixed since that line was added in 2010 - maybe I still have the test files somewhere.

**Comment by olivluca** [comment]
Well, it doesn't crash with the pictures I'm using, in any case I'd prefer a random crash (which I think it'd be easier to detect and debug) than an empty timage.
Then there's the other issue I raised in the mailing list thread but that's easily solved by not installing vampyre in the ide.

**Comment by galfar** [comment]
Looks like it's not crashing on select files anymore, removing the unregistering code.

**Comment by olivluca** [comment]
Thank you, but even if it still crashed I don't think that unregistering it would be correct (unless vampyre takes over the TPortableNetworkGraphic format but that's another can of worms).
