### ISSUE TITLE
Small issue with OPENGL_USE_DGL_HEADERS

### ISSUE THREAD

**Issue by Alexey-T** [galfar/imaginglib#5]
Win32, Lazarus.
When build mode OPENGL_USE_DGL_HEADERS is used, we have compile error in : Extras\Extensions\ImagingOpenGL.pas. 2 errors in lines 688, 875. Seems the reason is wrong boolean types (pascal boolean is used, while needed OpenGL boolean).

Thanks for your work on this component!

**Comment by galfar** [comment]
What version of dglOpenGL unit and Lazarus do you use? I cannot reproduce this with latest versions.

**Comment by Alexey-T** [comment]
@artem3213212 Pls answer about versions

**Comment by Artem3213212** [comment]
https://github.com/SaschaWillems/dglOpenGL + trunk laz

**Comment by galfar** [comment]
Ah it was actually Win64 where I got the error. I think that cast to Byte was some leftover from supporting GL headers from GLScene. It's removed now.

**Comment by Alexey-T** [comment]
Thanks!
